CREATE DATABASE doingsdone
	DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;
	
USE doingsdone;

CREATE TABLE projects (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	user_id INT UNSIGNED NOT NULL
);

CREATE TABLE tasks (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	date_limit TIMESTAMP NULL,
	task_file VARCHAR(255) NULL,
	status TINYINT(1) DEFAULT 0 NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	project_id INT UNSIGNED NOT NULL
);

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(128) UNIQUE NOT NULL,
	date_registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	password VARCHAR(64) NOT NULL
);

CREATE INDEX project_name ON projects(name);